inherit_gem:
  armitage-rubocop:
    - lib/rubocop.general.yml
    - lib/rubocop.rake.yml
    - lib/rubocop.rspec.yml

AllCops:
  TargetRubyVersion: 2.4.9
  Include:
    - lib/**/*.rb
    - spec/**/*.rb
    - Gemfile
    - Rakefile
    - sidekiq_portal.gemspec
    - bin/console
    - bin/rspec

# NOTE: support for old ruby versions
Style/RedundantBegin:
  Enabled: false

# NOTE: too situative
Metrics/ParameterLists:
  Enabled: false
