os: linux
dist: xenial
language: ruby
before_install: gem install bundler
script: bundle exec rspec
cache: bundler
jobs:
  fast_finish: true
  include:
  - rvm: 2.4.10
  - rvm: 2.5.8
  - rvm: 2.6.6
  - rvm: 2.7.1
  - rvm: ruby-head
  - rvm: jruby-head
  allow_failures:
  - rvm: ruby-head
  - rvm: jruby-head

# Added comment - 
